apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-06T06:13:00Z"
  labels:
    app: mysql
  name: mysql
  namespace: default
  resourceVersion: "7156"
  selfLink: /api/v1/namespaces/default/services/mysql
  uid: aaaf27ce-77cd-11ea-bf44-42010a80002c
spec:
  clusterIP: 10.24.6.82
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32550
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.68.30.234
