apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-06T07:45:59Z"
  generation: 2
  labels:
    app: orderdetailservice
  name: orderdetailservice
  namespace: default
  resourceVersion: "28042"
  selfLink: /apis/apps/v1/namespaces/default/deployments/orderdetailservice
  uid: a7ec6a80-77da-11ea-bf44-42010a80002c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: orderdetailservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orderdetailservice
    spec:
      containers:
      - env:
        - name: orderapi
          valueFrom:
            configMapKeyRef:
              key: orderapi
              name: orderdetailservice-config-agdb
        - name: userapi
          valueFrom:
            configMapKeyRef:
              key: userapi
              name: orderdetailservice-config-agdb
        - name: jagerservice
          valueFrom:
            configMapKeyRef:
              key: jagerservice
              name: orderdetailservice-config-agdb
        - name: jagerPort
          valueFrom:
            configMapKeyRef:
              key: jagerPort
              name: orderdetailservice-config-agdb
        image: kunal94vverma/orderdetailjag
        imagePullPolicy: Always
        name: orderdetailjag-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-06T07:46:02Z"
    lastUpdateTime: "2020-04-06T07:46:02Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-06T07:45:59Z"
    lastUpdateTime: "2020-04-06T07:46:02Z"
    message: ReplicaSet "orderdetailservice-7855848fd9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
