version: '3.4'

services:
  orderservice:
    image: kunal94vverma:OrderJaggerMYSQL
    ports:
      - "1111:8080"
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    networks: 
      - backend

  userservice:
    image: kunal94vverma:UserJaggerMYSQL
    environment:
      - server=localhost
      - password=password
      - userid=root
      - port=3333
    ports:
      - "2222:8080"
    depends_on:
      - mysql 
    build:
      context: .
      dockerfile: UserService/Dockerfile
    networks: 
      - backend

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3333:3306"
    networks: 
      - backend

networks: 
  backend: 
    driver: bridge

