apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-06T07:16:19Z"
  labels:
    app: jagerservice
  name: jagerservice
  namespace: default
  resourceVersion: "20617"
  selfLink: /api/v1/namespaces/default/services/jagerservice
  uid: 83069ee4-77d6-11ea-bf44-42010a80002c
spec:
  clusterIP: 10.24.3.5
  externalTrafficPolicy: Cluster
  ports:
  - name: 5775-to-5775-udp
    nodePort: 32731
    port: 5775
    protocol: UDP
    targetPort: 5775
  - name: 6831-to-6831-udp
    nodePort: 30153
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: 6832-to-6832-udp
    nodePort: 31303
    port: 6832
    protocol: UDP
    targetPort: 6832
  selector:
    app: jagerservice
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.192.43.220
