apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-04-06T06:06:24Z"
  generation: 2
  labels:
    app: jagerservice
  name: jagerservice
  namespace: default
  resourceVersion: "6704"
  selfLink: /apis/apps/v1/namespaces/default/deployments/jagerservice
  uid: be9c8266-77cc-11ea-bf44-42010a80002c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: jagerservice
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jagerservice
    spec:
      containers:
      - env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          valueFrom:
            configMapKeyRef:
              key: COLLECTOR_ZIPKIN_HTTP_PORT
              name: jagerservice-config-765k
        image: jaegertracing/all-in-one:latest
        imagePullPolicy: Always
        name: all-in-one-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-04-06T06:06:29Z"
    lastUpdateTime: "2020-04-06T06:06:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-04-06T06:06:24Z"
    lastUpdateTime: "2020-04-06T06:06:29Z"
    message: ReplicaSet "jagerservice-5569fbf78d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
