apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: "2020-04-06T05:50:10Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-central1
    failure-domain.beta.kubernetes.io/zone: us-central1-c
  name: pvc-78bc7647-77ca-11ea-bf44-42010a80002c
  resourceVersion: "2087"
  selfLink: /api/v1/persistentvolumes/pvc-78bc7647-77ca-11ea-bf44-42010a80002c
  uid: 7a4cb697-77ca-11ea-bf44-42010a80002c
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-volumeclaim
    namespace: default
    resourceVersion: "2075"
    uid: 78bc7647-77ca-11ea-bf44-42010a80002c
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-nagp-caa162a4-dyna-pvc-78bc7647-77ca-11ea-bf44-42010a80002c
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: failure-domain.beta.kubernetes.io/zone
          operator: In
          values:
          - us-central1-c
        - key: failure-domain.beta.kubernetes.io/region
          operator: In
          values:
          - us-central1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Bound
